language: cpp
script:
    - mkdir build
    - cd build && cmake ../ -DTEST=ON
    - cmake --build build
    - ctest --verbose build
compiler: clang
matrix:
  include:
    - os: osx
    - os: linux
      addons:
          apt:
            sources:
              - george-edison55-precise-backports
            packages:
              - cmake-data
              - cmake

