language: cpp
script:
    - chmod a+x scripts/*
    - ctest --build-and-test . build --build-generator Ninja -VV --build-two-config --test-command ctest -V
matrix:
  include:
    - os: osx
      before_install:
        - brew install ninja
    - os: linux
      compiler: clang
      addons:
          apt:
            sources:
              - george-edison55-precise-backports
              - ppa:nschloe/boost-nightly
            packages:
              - cmake-data
              - cmake
              - ninja-build
              - boost1.66
    - os: linux
      compiler: gcc
      addons:
          apt:
            sources:
              - george-edison55-precise-backports
              - ppa:nschloe/boost-nightly
            packages:
              - cmake-data
              - cmake
              - ninja-build
              - boost1.66
