language: cpp
script:
    - chmod a+x scripts/*
    - ctest --build-and-test . build --build-generator Ninja -VV --build-two-config --test-command ctest -V -DDONT_PREFER_CLANG=ON
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: osx
      before_install:
        - brew install ninja
    - os: linux
      addons:
          apt:
            sources:
              - george-edison55-precise-backports
            packages:
              - cmake-data
              - cmake
              - ninja-build
              - libboost-all-dev
