include ( CMakePushCheckState )
function ( checkandaddflag flag addto )
  set ( NAME "accepts_flag_${flag}" )
  string ( MAKE_C_IDENTIFIER ${NAME} NAME )
  string ( REPLACE "__" "_" NAME ${NAME} )
  string ( REPLACE "__" "_" NAME ${NAME} )
  cmake_push_check_state ( RESET )
  set ( CMAKE_REQUIRED_FLAGS "${${addto}} ${flag}" )
  check_cxx_compiler_flag ( "${flag}" "${NAME}" )
  cmake_pop_check_state ()
  if ( ${NAME} )
    set ( ${addto} "${${addto}} ${flag}" PARENT_SCOPE )
    list ( APPEND "${addto}_LIST" ${flag} )
    set ( "${addto}_LIST" ${${addto}_LIST} PARENT_SCOPE )
  endif ()
endfunction ()
