include ( rewrite_link_libraries )
function ( copy_target_properties TARGET SUFFIX )
  foreach ( PROP INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS COMPILE_FLAGS )
    get_target_property ( VALUE ${TARGET} ${PROP} )
    if ( VALUE )
      set_target_properties ( ${TARGET}${SUFFIX} PROPERTIES ${PROP} "${VALUE}" )
    endif ()
  endforeach ()
  foreach ( PROP LINK_LIBRARIES INTERFACE_LINK_LIBRARIES )
    get_target_property ( VALUE ${TARGET} ${PROP} )
    if ( VALUE )
      rewrite_link_libraries ( "${VALUE}" VALUE ${SUFFIX} )
      set_target_properties ( ${TARGET}${SUFFIX} PROPERTIES ${PROP} "${VALUE}" )
    endif ()
  endforeach ()
endfunction ()
