find_package ( PkgConfig )
option ( VALGRIND "Enable valgrind" ON )
if ( VALGRIND )
  find_program ( VALGRIND_PATH valgrind )
  if ( VALGRIND_PATH )
    set ( VALGRIND_OPTS "" CACHE STRING "Extra options for valgrind" )
    option ( VALGRIND_XML "Output valgrind results to XML" OFF )
    pkg_check_modules ( valgrind QUIET IMPORTED_TARGET valgrind )
    if ( TARGET PkgConfig::valgrind AND test )
      add_library ( valgrind INTERFACE )
      set_target_properties ( valgrind PROPERTIES INTERFACE_LINK_LIBRARIES PkgConfig::valgrind )
      find_file ( VALGRIND_MEMCHECK_H memcheck.h PATHS ${valgrind_INCLUDEDIR} )
      if ( VALGRIND_MEMCHECK_H )
        target_compile_definitions ( valgrind INTERFACE -DHAVE_VALGRIND_MEMCHECK_H )
      endif ()
    endif ()
  endif ()
endif ()
if ( NOT TARGET valgrind )
  add_library ( valgrind INTERFACE )
endif ()
install ( TARGETS valgrind EXPORT dvforms COMPONENT devel )
include ( FindPackageHandleStandardArgs )
find_package_handle_standard_args ( valgrind REQUIRED_VARS VALGRIND_PATH )
