function ( rewrite_link_libraries LIBS OUT SUFFIX )
  set ( RETURN )
  foreach ( LIB IN ITEMS ${LIBS} )
    if ( TARGET "${LIB}${SUFFIX}" )
      list ( APPEND RETURN "${LIB}${SUFFIX}" )
    else ()
      list ( APPEND RETURN "${LIB}" )
    endif ()
  endforeach ()
  set ( ${OUT} ${RETURN} PARENT_SCOPE )
endfunction ()
